import { Loading } from "@nextui-org/react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import useSWR from "swr";
import styles from "../../styles/Home.module.css";
export default function Home() {
  const { id } = useRouter().query;
  const fetcher = (...args) => fetch(...args).then((res) => res.json());
  const { data, error, isLoading } = useSWR(
    `https://equran.id/api/surat/${id}`,
    fetcher
  );

  if (error) return <div>failed to load</div>;
  if (isLoading)
    return (
      <div className={styles.main}>
        <Loading color={"currentColor"} />;
      </div>
    );

  return (
    <>
      <Head>
        <title>
          {data.nama_latin} | {`Al-qu'ran Indonesia`}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-10 lg:mx-80">
        <div className="mb-10 text-center">
          <h1 className="text-xl font-bold">
            {data.nomor}. {data.nama_latin} {`(${data.jumlah_ayat})`}
          </h1>
          <h1 className="mb-4 italic text-sm">{data.arti}</h1>
          <h1
            className="text-justify m-auto"
            dangerouslySetInnerHTML={{ __html: data.deskripsi }}
          />
        </div>
        <h1 className="m-auto gap-7 flex flex-col">
          {data.ayat.map((e, i) => (
            <div key={i} className="bg-red-900 rounded-lg px-2 py-2">
              <h1 className="text-justify mb-2">
                {e.nomor}. {e.ar}
              </h1>
              <h1 className="text-justify mb-2">{e.tr}</h1>
              <h1 className="italic text-justify">{`Artinya: ${e.idn}`}</h1>
            </div>
          ))}
        </h1>
        <audio
          controls
          className="fixed right-4 z-50 bottom-4 h-[40px] w-[240px]"
        >
          <source src={data.audio} type="audio/mpeg" />
        </audio>
        <div className="flex flex-col justify-between left-4 fixed z-50 bottom-4 text-center">
          {data.surat_sebelumnya != true ? (
            <Link href={`/`} className="bg-red-900 rounded-xl py-1 px-4 mb-4">
              {"Beranda"}
            </Link>
          ) : (
            <></>
          )}
          {data.surat_sebelumnya != true ? (
            <Link
              href={`/al-quran/${data.surat_sebelumnya.id ?? "/"}`}
              className={`${
                data.surat_sebelumnya === false ? null : `bg-red-900`
              } rounded-xl py-1 px-4 hover:cursor-pointer mb-4 w-60`}
            >
              {`< ${data.surat_sebelumnya.nama_latin ?? "Beranda"}`}
            </Link>
          ) : (
            <div></div>
          )}
          <Link
            href={`/al-quran/${data.surat_selanjutnya.id ?? "/"}`}
            className="bg-red-900 rounded-xl py-1 px-4"
          >
            {`${data.surat_selanjutnya.nama_latin ?? "Beranda"} >`}
          </Link>
        </div>
      </div>
    </>
  );
}
