import Head from "next/head";
import useSWR from "swr";
import styles from "../../styles/Home.module.css";
import { useRouter } from "next/router";
import { Loading } from "@nextui-org/react";
import Layout from "../../components/layout";
export default function Home() {
  const route = useRouter();

  const fetcher = (...args) => fetch(...args).then((res) => res.json());
  const { data, error, isLoading } = useSWR(
    "https://www.emsifa.com/api-wilayah-indonesia/api/provinces.json",
    fetcher
  );

  if (error) return <div>failed to load</div>;
  if (isLoading)
    return (
      <div className={styles.main}>
        <Loading />
      </div>
    );

  return (
    <Layout>
      <Head>
        <title>{`Daerah Indonesia`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fp.png" />
      </Head>

      <div className="m-10 my grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        {data.map((e, i) => (
          <div
            className="text-white hover:cursor-pointer bg-red-900 px-4 py-4 rounded-lg hover:scale-110 duration-500 hover:border"
            onClick={() => {
              route.push(`provinsi/${e.id}`);
            }}
            key={i}
          >
            <h1>{e.name}</h1>
          </div>
        ))}
      </div>
    </Layout>
  );
}
